### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by Steffeng90** [Steffeng90/AnimaRPG#19]
GEschlagener Gegner fliegt weg bei Tod
X Nahrungmit Werten versehen
Feedback kleiner
X KArte 3 brot in gold
X Raidderlangsamer
X archer schneller
X Pfeiel an Grenzgebiet gehen nicht kaputt

X Error bei Healer
ava.lang.NullPointerException: Attempt to invoke virtual method 'com.badlogic.gdx.physics.box2d.World com.mygdx.anima.screens.Playscreen.getWorld()' on a null object reference
                      at com.mygdx.anima.sprites.character.zauber.fixtures.HeilzauberAOE.<init>(HeilzauberAOE.java:23)
                      at com.mygdx.anima.sprites.character.enemies.raider.RaiderHealer.heilen(RaiderHealer.java:140)
                      at com.mygdx.anima.sprites.character.enemies.raider.RaiderHealer.update(RaiderHealer.java:50)

**Comment by Steffeng90** [comment]
Karte2: Baumstamm hat keine Box, oberen Bereich kann man optimieren.
Events: Bei Dorf sollte auf alle Fälle der Questbereich weitergehen. auch wenn man das Schwert nicht geholt hat
Beim Schlagen laufen gegner kruz nach unten , weil Bounds nicht richtig angezeigt werden.
